"""completed added to task and project

Revision ID: 44f056c07ae8
Revises: a4b44b324a12
Create Date: 2026-09-17 16:38:25.553888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f056c07ae8'
down_revision = 'a4b44b324a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('completed')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
