"""part task many to many

Revision ID: a12fa14db11d
Revises: f9a08e81ae57
Create Date: 2026-09-16 18:39:43.278504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12fa14db11d'
down_revision = 'f9a08e81ae57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_parts',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_task_parts_part_id_parts')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_parts_task_id_tasks')),
    sa.PrimaryKeyConstraint('task_id', 'part_id')
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_parts_task_id_tasks'), type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_parts_task_id_tasks'), 'tasks', ['task_id'], ['id'])

    op.drop_table('task_parts')
    # ### end Alembic commands ###
