"""tools split from parts

Revision ID: a4b44b324a12
Revises: a12fa14db11d
Create Date: 2026-09-16 20:38:49.491242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b44b324a12'
down_revision = 'a12fa14db11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tools_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_tools',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_tools_task_id_tasks')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_task_tools_tool_id_tools')),
    sa.PrimaryKeyConstraint('task_id', 'tool_id')
    )
    op.drop_table('task_parts')
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_parts_task_id_tasks'), 'tasks', ['task_id'], ['id'])
        batch_op.drop_column('part_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_parts_task_id_tasks'), type_='foreignkey')
        batch_op.drop_column('task_id')

    op.create_table('task_parts',
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('part_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_task_parts_part_id_parts')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_parts_task_id_tasks')),
    sa.PrimaryKeyConstraint('task_id', 'part_id')
    )
    op.drop_table('task_tools')
    op.drop_table('tools')
    # ### end Alembic commands ###
